export const titleTablePatient = {
  lastName: "Фамилия",
  name: "Имя",
  patronymic: "Отчество",
  dateOfBirth: "Дата рождения",
  phoneNumber: "Номер телефона",
  sex: "Пол",
  groupClient: "Группа пациентов",
  doctor: "Врач",
  index: "Индекс",
  country: "Страна",
  region: "Область",
  city: "Город",
  street: "Улица",
  numberHouse: "Номер дома",
  documentType: "Тип документа",
  seriesDocument: "Серия",
  numberDoc: "Номер",
  issuedByWhom: "Кем выдан",
  dateOfIssue: "Дата выдачи",
};
