export const titleTablePatient = {
  personData: {
    title: "Личные данные",
    lastName: "Фамилия",
    name: "Имя",
    patronymic: "Отчество",
    dateOfBirth: "Дата рождения",
    phoneNumber: "Номер телефона",
    sex: "Пол",
    groupClient: "Группа пациентов",
    doctor: "Врач",
  },
  addressData: {
    title: "Адрес",
    index: "Индекс",
    country: "Страна",
    region: "Область",
    city: "Город",
    street: "Улица",
    numberHouse: "Номер дома",
  },
  passportData: {
    title: "Паспортные данные",
    documentType: "Тип документа",
    seriesDocument: "Серия",
    numberDoc: "Номер",
    issuedByWhom: "Кем выдан",
    dateOfIssue: "Дата выдачи",
  },
};
