export const FETCH_GET_PATIENTS_LIST = "FETCH_GET_PATIENTS_LIST";
export const FETCH_NEW_PATIENT = "FETCH_NEW_PATIENT";
export const FETCH_SELECTED_PATIENT = "FETCH_SELECTED_PATIENT";
export const ON_EDIT_MODE = "ON_EDIT_MODE";
export const EXIT_EDIT_MODE = "EXIT_EDIT_MODE";
export const SAVE_ERROR = "SAVE_ERROR";
